// Reading types.
//
// The reading phase consumes the survey's CompilerOutput (Profile + Brief
// + Choice) and produces a fan-out, card-flipped portrait of the user-at-
// the-fork. New architecture (replaces the older Plan-and-Write):
//
//   1. INTRO — short monologue establishing presence. Pre-baked for demo
//      (see fixtures.ts); director+actor generated in production.
//
//   2. PER-CARD FAN-OUT — at the start of each round (round N = the
//      user is about to flip their Nth card), spawn one director+actor
//      pair per still-face-down slot, IN PARALLEL. Each thread treats
//      its slot as the hypothetical-next-flip. None of these threads
//      know the faces of slots they're not assigned. When the user
//      picks a slot, we look up the pre-computed monologue for
//      [round, picked-slot] and deliver it.
//
//   3. CLOSING — after all four flips, one director+actor pair
//      synthesizes a structural takeaway across the full revealed arc.
//
// Mirror-not-oracle: cards illuminate the user's RELATIONSHIP to the
// fork, never the answer. The director produces understanding; the actor
// produces utterance. The split is load-bearing — the director can route
// to deep-tier cloud Claude; the actor can eventually route to local
// uncensored OSS LLMs.

import type { DrawnCards, Profile } from '../types';
import type { PickEvent } from '../survey';

// ─── ReadingInputs — internal Seer state shape ─────────────────
// Built INSIDE Seer's constructor from SeerOpts. Kept as its own type
// because the existing per-card / chat / closing code reads from it.

export type ReadingInputs = {
  profile: Profile;
  /** Generated by directorIntro (or '<demo>' when preferred_intro is
   *  supplied). All per-card director + closing director calls read it. */
  prose_brief: string;
  drawn: DrawnCards;
  /** Demo-path short-circuit: when set, intro generation is skipped
   *  and this fixture-authored intro is used verbatim. */
  preferred_intro?: Monologue;
};

// ─── Outcomes ───────────────────────────────────────────────
//
// An Outcome is a coherent picture of one way the intention could open
// onto reality. Seeded by the survey-side Augur agent before the Seer
// is constructed; passed in as Seer input; consumed by all director
// calls (per-card, closing, intro) for texture. Actor does NOT read
// outcomes directly — the director embeds specifics from outcomes into
// the Sets it produces, and the actor voices the Set.
//
// `document` is FREELY-formatted markdown — no enforced sections (the
// Augur prompt suggests a template but the model can blow past it).
// Per the .txt-team / Castillo research on JSON-vs-prose: structured
// JSON only where the next consumer is the engine (id + label); prose
// where the next consumer is another LLM (the document body).
export type Outcome = {
  id: string;          // stable across session updates (e.g., 'outcome-cat-yes')
  label: string;       // short tag, 3-6 words ("jake gets a cat")
  document: string;    // freely-written markdown, present tense, vivid
};

// ─── Intro director ─────────────────────────────────────────

export type IntroDirectorInput = {
  profile: Profile;
  intention: string;
  surveyHistory: PickEvent[];
  outcomes: Outcome[];
  /** The narrative cross-section the survey's detective built. Forms
   *  the SPINE of the prose_brief — the director writes around the
   *  fork / present_pressure / past_root / stakes slots, weaving
   *  picks + cast + hooks around them. May be null when the survey
   *  closed before the detective committed a story. */
  story?: import('../survey').StoryObject | null;
};

// ─── Per-card director (prepares the Set the seer inhabits) ─────

/** Narrative-arc role for a flip. Borrowed from Dramatron's scene labels.
 *  Mapped from flip ORDER (not slot identity), so the same slot might be
 *  'opening' in one reading and 'turning' in another, depending on when
 *  the user chose to flip it. */
export type NarrativeRole = 'opening' | 'rising' | 'turning' | 'closing';

/** A Set — Stanislavski "given circumstances" for the performer.
 *  Not content. Not a script. Interior state to inhabit. The actor
 *  walks into the set when the card flips and performs from it; words
 *  emerge from the prepared mind rather than translation. */
export type Set = {
  position_id: string;             // which slot this set is for
  card_id: number;                 // the card face at that slot
  flip_round: number;              // 1..4 — when in the reading this happens
  narrative_role: NarrativeRole;

  /** What just clicked — the specific resonance between THIS card and
   *  THIS person; the small "ah" the reader has at the moment of the
   *  flip. 1-2 sentences. The seed of the beat. */
  click: string;
  /** The thread in the profile this card has surfaced; what the reader
   *  is now watching for in the participant. 1 sentence. */
  attending: string;
  /** Beat motivation — confront, comfort, warn, illuminate, agitate,
   *  settle. Single verb-phrase. NOT a takeaway. */
  intent: string;
  /** Specific facts and hunches from the profile this card licenses
   *  the seer to use. The seer chooses which to surface and which to
   *  hold back — under-specifying is itself a craft move. 0-5 items. */
  knows: string[];
  /** What is genuinely uncertain. May be voiced AS uncertainty — that
   *  is far eerier than false confidence. 0-1 sentences. */
  uncertainty: string;
  /** One line connecting this beat back to THE choice. The specific
   *  angle this card illuminates the user-at-the-fork from. */
  through_line: string;
  /** Optional. A reframe — "you believe X about yourself / the
   *  situation; the card licenses a different angle." When populated,
   *  the actor is invited to voice the swap directly: 'you think
   *  you're hesitating because of him. you're hesitating because of
   *  you.' The director emits this ONLY when the card genuinely
   *  supports a reframe; most beats won't have one. Null/omitted
   *  otherwise. */
  reframe?: {
    /** What the user currently believes (about themselves, the
     *  situation, the other person). Concrete, citable from picks. */
    user_belief: string;
    /** What the card licenses as the alternative angle. Specific. */
    cards_invitation: string;
  };
};

/** @deprecated Use Set. Kept transiently for any consumer still importing. */
export type ClinicalIntent = Set;

// ─── Actor output (the voiced layer) ───────────────────────────

export type Monologue = {
  /** The spoken text. Lowercase voice, mirror register, 2-4 sentences
   *  for beats; 1 short line for intro; 1 sentence for outro. */
  text: string;
  /** Optional invitation for user response. If non-empty, UI may
   *  surface it as a hint above the chat box. */
  prompt_to_user?: string;
};

// ─── Closing ───────────────────────────────────────────────────

export type ClosingIntent = {
  /** ONE-sentence structural takeaway. The frame the user carries
   *  out of the tent. */
  takeaway: string;
  /** Pacing / tone direction for the actor's outro delivery. */
  director_notes: string;
  /** Optional closing mantra — a short declarative line, no markdown
   *  or emoji, ticker-tape-printable. Generated by a separate mantra
   *  agent after the 4th flip (Phase J). The actor may voice it as
   *  the outro's final beat, AND the UI renders it post-outro as the
   *  user's takeaway artifact. Null when the mantra agent hasn't run
   *  or didn't produce a usable line. */
  mantra?: string | null;
};

// ─── Engine state ──────────────────────────────────────────────

export type ReadingPhase =
  | 'idle'              // not started
  | 'thinking'          // intro generation in flight (only if no preferred_intro)
  | 'intro'             // intro typewriter active
  | 'awaiting_flip'     // user can pick a face-down card or chat
  | 'flipping'          // CSS-3D flip animation playing
  | 'beat_pending'      // monologue not yet ready (fan-out still in flight)
  | 'beat'              // monologue typewriter active
  | 'chat_pending'      // actor generating reply to a user chat message
  | 'closing_thinking'  // director + actor running after the 4th flip
  | 'outro'             // closing monologue typewriter active
  | 'done'              // reading complete; chat may still be possible
  | 'error';

export type ChatSpeaker = 'user' | 'seer';

export type ChatMessage = {
  speaker: ChatSpeaker;
  text: string;
};

export type RevealedSlot = {
  position_id: string;
  card_id: number;
  set: Set;
  monologue: Monologue;
};

export type ReadingState = {
  inputs: ReadingInputs;
  phase: ReadingPhase;
  intro: Monologue | null;
  outro: Monologue | null;
  revealed: RevealedSlot[];           // in flip order
  /** The slot the user has picked for the current flip (or is being voiced). */
  current_slot: string | null;
  /** Which seer layer we're awaiting, for catchphrase selection. null = no wait. */
  awaiting_layer: 'director' | 'actor' | null;
  /** Live invitation from the seer for the user to respond. Set when a
   *  delivered Monologue carried a prompt_to_user; cleared when the user
   *  responds (picks a card or sends a chat). */
  active_prompt_to_user: string | null;
  chat: ChatMessage[];
  error?: string;
};

export type ReadingListener = (state: ReadingState) => void;

// ─── Agent I/O (for the call wrappers) ─────────────────────────

export type PerCardDirectorInput = {
  profile: Profile;
  prose_brief: string;
  /** Outcomes (Augur-seeded) the seer carries through this session.
   *  Director picks WHICH outcome this card sharpens + may embed a
   *  specific from that outcome into the Set. Actor never sees these. */
  outcomes: Outcome[];
  /** All slots in the spread (with prompt_labels) so the model knows
   *  the structure, but face information is restricted to this_slot +
   *  already-revealed. */
  spread_id: string;
  spread_name: string;
  all_positions: Array<{ id: string; role: string; prompt_label: string }>;
  /** The slot this thread is reading for, including its card face. */
  this_slot: {
    position_id: string;
    role: string;
    prompt_label: string;
    card_id: number;
    card_name: string;
    card_keywords: string[];
    card_upright_meaning: string;
  };
  flip_round: number;
  /** Cards already revealed in this session, with their delivered beats. */
  revealed_history: Array<{
    position_id: string;
    card_name: string;
    beat_text: string;
  }>;
  /** Chat exchanges so far. */
  chat_history: ChatMessage[];
};

export type PerCardActorInput = {
  profile: Profile;
  prose_brief: string;
  set: Set;
  /** The card face being voiced. */
  card: { name: string; keywords: string[]; upright_meaning: string };
  /** Slot role (e.g. "what surrounds the choice"). */
  slot_label: string;
  revealed_history: Array<{ position_id: string; card_name: string; beat_text: string }>;
  chat_history: ChatMessage[];
};

export type IntroActorInput = {
  profile: Profile;
  prose_brief: string;
};

export type ClosingDirectorInput = {
  profile: Profile;
  prose_brief: string;
  outcomes: Outcome[];
  revealed: RevealedSlot[];
  chat_history: ChatMessage[];
  /** The detective's StoryObject — same one the intro director read.
   *  Closing director uses past_root / present_pressure / fork.a /
   *  fork.b to shape the takeaway: the lens the user carries out is
   *  about their RELATIONSHIP to the fork, not advice. */
  story?: import('../survey').StoryObject | null;
  /** Hypotheses that survived the survey without integration or
   *  refutation, sorted by age_in_turns DESC. The closing director
   *  MAY take a risky swing at one as the loaded probe at the end
   *  ("there's something you haven't said about X — i'm guessing it's
   *  because Y"). Optional theatrical move. Older probes are more
   *  durable; the first item is the most diagnostically interesting. */
  heldProbes?: import('../survey').Hypothesis[];
};

export type ClosingActorInput = {
  profile: Profile;
  prose_brief: string;
  revealed: RevealedSlot[];
  chat_history: ChatMessage[];
  closing: ClosingIntent;
};

export type ChatActorInput = {
  profile: Profile;
  prose_brief: string;
  revealed: RevealedSlot[];
  chat_history: ChatMessage[];
  user_message: string;
};
